language: python
python:
  - "2.7"
services: mongodb
install: "pip install -r requirements.txt"
script: python test.py

# Credit: http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git submodule sync
    - git submodule update --init --recursive